// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEFTPWKG1DdzCnumtchWDaCQueSPTScFY',
    appId: '1:960772471004:web:49638f28eb3dc1ce979c19',
    messagingSenderId: '960772471004',
    projectId: 'flutterfire-ui-codelab-dbd19',
    authDomain: 'flutterfire-ui-codelab-dbd19.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-dbd19.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjhrhOKCyQLHC8r6H3Zkyz1Myg9Fck-nk',
    appId: '1:960772471004:android:5bab103378a282fc979c19',
    messagingSenderId: '960772471004',
    projectId: 'flutterfire-ui-codelab-dbd19',
    storageBucket: 'flutterfire-ui-codelab-dbd19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC191jteH_3ywOg63yOgEIafcWnsCtiuh4',
    appId: '1:960772471004:ios:9a01caf53a12f394979c19',
    messagingSenderId: '960772471004',
    projectId: 'flutterfire-ui-codelab-dbd19',
    storageBucket: 'flutterfire-ui-codelab-dbd19.firebasestorage.app',
    iosBundleId: 'com.example.start',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC191jteH_3ywOg63yOgEIafcWnsCtiuh4',
    appId: '1:960772471004:ios:9a01caf53a12f394979c19',
    messagingSenderId: '960772471004',
    projectId: 'flutterfire-ui-codelab-dbd19',
    storageBucket: 'flutterfire-ui-codelab-dbd19.firebasestorage.app',
    iosBundleId: 'com.example.start',
  );
}
